const Map<String, String> ar = {
  "Title": "العنوان",
  "Setting": "الاعداتات",
  "Notification": "الاشعارات",
  "My List": "قائمتي",
  "Courses": "كورسات",
  "Home": "رئيسية",
  "description": "وصف",
  "Night mode": "وضع اليلي",
  "save": "حفظ",
  "About us": "من نحن",
  "Profile": "الملف الشخصي",
  "Language": "اللغة",
  "is Intro": "تعريفي؟",
  "video View image": "صورة فيديو",
  "error": "خطأ",
  "Are you sure!": "هل انت متأكد!",
  "when delete the course all his videos well be deleted": "عندما تحذف الكورس كل فيديواهات خاصة به سوف تحذف",
  "when delete the user all his information well be deleted": "عندما تحذف المستخدم كل معلوماته سوف تحذف",
  "add": "أضافة",
  "Attention!": "انتباه!",
  "support": "الدعم",
  "we send an Email to your Email account please check it.": "سوف نرسل اليك ايميل الى بريدك الكتروني يرجى تأكد منه.",
  "List View": "قائمة تشغيل",
  "edit profile": "تعديل الملف الشخصي",
  "  <Press to Edit profile >": "  <أضغط للتعديل الملف الشخصي>",
  "  <Press to Change Play >": "  <أضغط للتغير الخظة الدفع>",
  "delete listView": "حذف القائمة",
  "New playList": "أضافة قائمة جديدة",
  "press Bottom to create": "أضغط الزر للانشاء",
  "Welcome to Online Course": "Welcome to Online Course",
  "We will help you sharpen your knowledge and skills.": "سوف نساعدك على صقلِ مهارارتك و معلوماتك",
  "Free Courses": "كورسات مجانية",
  "More than 300 courses with different languages with comprehensive learning paths.": "اكثر من 300 كورسات المختلفة اللغات مع مسارات تعليم شاملة",
  "your one playlist": "قائمة التشغيل خاصة بك",
  "Create a playlist and Add your Important Videos to it.": "انشأ قائمة التشغل  الخاصة بك وأضف عليها الدروس المهمة.",
  "Getting Started": "لنبدأ",
  "Skip": "تخطي",
  "your password": "كلمة السر",
  "forget password ?": "نسيت كلمة السر؟",
  "Login": "تسجيل الدخول",
  "course View image": "صورة الكورس",
  "List View Name": "اسم كورس",
  "Expected Time To Finish": "الوقت المتوقع للانتهاء من كورس",
  "Expected time to finish :": "الوقت المتوقع للانتهاء من كورس:",
  "check your internet connection": "تأكد من الاتصال بالانترنت",
  "enter your email": "ادخل ايميلك",
  "empty field": "حقل فارغ",
  "not email": "ليس بأيميل",
  "you need to enter email only": "ادل ايميل فقط",
  "telegram": "تيليغرام",
  "enter your password": "ادخل كلمة السر",
  "short password": "كلمة سر قصيرة",
  "short password must more than 6 characters": "short password must more than 6 characters",
  "Dio": "لمحة عنك",
  "first name": "الاسم الأول",
  "last name": "الاسم الأخير",
  "save changes": "حفظ التغيرات",
  "You have account?": "تمتلك حساب بالفعل؟",
  "SignIn": "تسجيل الدخول",
  "search": "بحث",
  "Search Word": "كلمة البحث",
  "you are not subscript": "انت لست متابع الأن",
  "dont have account?": "ليس لديك حساب؟",
  "SignUp": "الاشتراك",
  "Education is a passport to the future": "العلم هو جواز سفر للمستقبل",
  "Mention": "للتنبيه",
  "Dont forget you are Using mobile data": "انتبه انت تستخدم بيانات الهاتف",
  "You are offline,connect to internet than restart the App": "انت غير متصل بالانترنت تأكد من اتصالك ثم اعد التشغيل تطبيق",
};
