const Map<String, String> en = {
  "Title": "Title",
  "Setting": "Setting",
  "Notification": "Notification",
  "My List": "My List",
  "Courses": "Courses",
  "Home": "Home",
  "description": "description",
  "Night mode": "Night mode",
  "save": "save",
  "About us": "About us",
  "Profile": "Profile",
  "Language": "Language",
  "is Intro": "is Intro",
  "video View image": "video View image",
  "error": "error",
  "Are you sure!": "Are you sure!",
  "when delete the course all his videos well be deleted": "when delete the course all his videos well be deleted",
  "when delete the user all his information well be deleted": "when delete the user all his information well be deleted",
  "add": "add",
  "Attention!": "Attention!",
  "support": "support",
  "we send an Email to your Email account please check it.": "we send an Email to your Email account please check it.",
  "List View": "List View",
  "edit profile": "edit profile",
  "  <Press to Edit profile >": "  <Press to Edit profile >",
  "  <Press to Change Play >": "  <Press to Change Play >",
  "delete listView": "delete listView",
  "New playList": "New playList",
  "press Bottom to create": "press Bottom to create",
  "Welcome to Online Course": "Welcome to Online Course",
  "We will help you sharpen your knowledge and skills.": "We will help you sharpen your knowledge and skills.",
  "Free Courses": "Free Courses",
  "More than 300 courses with different languages with comprehensive learning paths.": "More than 300 courses with different languages with comprehensive learning paths.",
  "your one playlist": "your one playlist",
  "Create a playlist and Add your Important Videos to it.": "Create a playlist and Add your Important Videos to it.",
  "Getting Started": "Getting Started",
  "Skip": "Skip",
  "your password": "your password",
  "forget password ?": "forget password ?",
  "Login": "Login",
  "course View image": "course View image",
  "List View Name": "List View Name",
  "Expected Time To Finish": "Expected Time To Finish",
  "Expected time to finish :": "Expected time to finish :",
  "check your internet connection": "check your internet connection",
  "enter your email": "enter your email",
  "empty field": "empty field",
  "not email": "not email",
  "you need to enter email only": "you need to enter email only",
  "telegram": "telegram",
  "enter your password": "enter your password",
  "short password": "short password",
  "short password must more than 8 characters": "short password must more than 8 characters",
  "Dio": "Dio",
  "first name": "first name",
  "last name": "last name",
  "save changes": "save changes",
  "You have account?": "You have account?",
  "SignIn": "SignIn",
  "search": "search",
  "Search Word": "Search Word",
  "you are not subscript": "you are not subscript",
  "dont have account?": "don't have account?",
  "SignUp": "SignUp",
  "Education is a passport to the future": "Education is a passport to the future",
  "Mention": "Mention",
  "Dont forget you are Using mobile data": "Don't forget you are Using mobile data",
  "You are offline,connect to internet than restart the App": "You are offline,connect to internet than restart the App",
};
